version: '2'

services:
  web:
    build:
      context: ./
      dockerfile: web.dockerfile
    volumes:
      - ./:/var/www
    ports:
      - "8080:80"
    links:
      - app
  app:
    build:
      context: ./
      dockerfile: app.dockerfile
    volumes:
      - ./:/var/www
    links:
      - db
      # - cache
    environment:
      - "DB_PORT=3306"
      - "DB_HOST=db"
      # - "REDIS_PORT=6379"
      # - "REDIS_HOST=cache"
  db:
    image: mysql:5.6
    volumes:
      - mysql:/var/lib/mysql
    environment:
      - "MYSQL_DATABASE=homestead"
      - "MYSQL_USER=homestead"
      - "MYSQL_PASSWORD=secret"
      - "MYSQL_ROOT_PASSWORD=secret"
    ports:
      - "33061:3306"
volumes:
  mysql:
